apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-platform
  namespace: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/imenH-cloud/devops-education-platform.git
    targetRevision: main
    path: devops-education-platform-gitops/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: education
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
