-- Load initial data
INSERT INTO teacher ("indexNumber", cin, "firstName", surname, gender, address, telephone, email, specialization) VALUES ('T001', 111, 'Imen', 'Hamada', 'F', 'Tozeur', '01234567', 'imen@school.com', 'Math');
INSERT INTO teacher ("indexNumber", cin, "firstName", surname, gender, address, telephone, email, specialization) VALUES ('T002', 222, 'Marie', 'Curie', 'F', 'Paris', '01234568', 'marie@school.com', 'Physics');
INSERT INTO teacher ("indexNumber", cin, "firstName", surname, gender, address, telephone, email, specialization) VALUES ('T003', 333, 'Albert', 'Einstein', 'M', 'Berlin', '01234569', 'albert@school.com', 'Physics');
INSERT INTO teacher ("indexNumber", cin, "firstName", surname, gender, address, telephone, email, specialization) VALUES ('T004', 444, 'Ada', 'Lovelace', 'F', 'London', '01234570', 'ada@school.com', 'IT');
INSERT INTO parent ("firstName", "lastName", email, "phoneNumber", "NCIN", address, "typeInsurance", "Numeroinsurance", job) VALUES ('Jean', 'Martin', 'jean@email.com', '0612345678', 111, 'Paris', 'Mutuelle', 'M123', 'Engineer');
INSERT INTO parent ("firstName", "lastName", email, "phoneNumber", "NCIN", address, "typeInsurance", "Numeroinsurance", job) VALUES ('Sophie', 'Bernard', 'sophie@email.com', '0623456789', 222, 'Lyon', 'SS', 'S234', 'Teacher');
INSERT INTO parent ("firstName", "lastName", email, "phoneNumber", "NCIN", address, "typeInsurance", "Numeroinsurance", job) VALUES ('Michel', 'Durand', 'michel@email.com', '0634567890', 333, 'Marseille', 'Mutuelle', 'M345', 'Doctor');
INSERT INTO parent ("firstName", "lastName", email, "phoneNumber", "NCIN", address, "typeInsurance", "Numeroinsurance", job) VALUES ('Isabelle', 'Petit', 'isabelle@email.com', '0645678901', 444, 'Toulouse', 'SS', 'S456', 'Lawyer');
INSERT INTO classroom (name, capacity, grade, "academicYear", location, "Specialization") VALUES ('Class A', 15, 'L1', '2024-2025', 'Building A', 'General');
INSERT INTO classroom (name, capacity, grade, "academicYear", location, "Specialization") VALUES ('Class B', 16, 'L2', '2024-2025', 'Building B', 'General');
INSERT INTO classroom (name, capacity, grade, "academicYear", location, "Specialization") VALUES ('Class C', 18, 'L3', '2024-2025', 'Building C', 'General');
INSERT INTO student ("firstName", "numeroInscriptio", "lastName", email, "dateOfBirth", "phoneNumber", address, "enrollmentDate", "parentId", "classroomId") VALUES ('Lucas', 'S001', 'Martin', 'lucas@student.com', '2012-05-15', '0612', 'Paris', '2024-09-01', 1, 1);
INSERT INTO student ("firstName", "numeroInscriptio", "lastName", email, "dateOfBirth", "phoneNumber", address, "enrollmentDate", "parentId", "classroomId") VALUES ('Emma', 'S002', 'Martin', 'emma@student.com', '2014-08-22', '0613', 'Paris', '2024-09-01', 1, 1);
INSERT INTO student ("firstName", "numeroInscriptio", "lastName", email, "dateOfBirth", "phoneNumber", address, "enrollmentDate", "parentId", "classroomId") VALUES ('Thomas', 'S003', 'Bernard', 'thomas@student.com', '2011-03-10', '0623', 'Lyon', '2024-09-01', 2, 2);
INSERT INTO student ("firstName", "numeroInscriptio", "lastName", email, "dateOfBirth", "phoneNumber", address, "enrollmentDate", "parentId", "classroomId") VALUES ('Julie', 'S004', 'Bernard', 'julie@student.com', '2013-11-30', '0624', 'Lyon', '2024-09-01', 2, 2);
INSERT INTO student ("firstName", "numeroInscriptio", "lastName", email, "dateOfBirth", "phoneNumber", address, "enrollmentDate", "parentId", "classroomId") VALUES ('Camille', 'S005', 'Durand', 'camille@student.com', '2010-09-12', '0634', 'Marseille', '2024-09-01', 3, 3);
INSERT INTO student ("firstName", "numeroInscriptio", "lastName", email, "dateOfBirth", "phoneNumber", address, "enrollmentDate", "parentId", "classroomId") VALUES ('Nathan', 'S006', 'Durand', 'nathan@student.com', '2015-01-25', '0635', 'Marseille', '2024-09-01', 3, 3);
INSERT INTO student ("firstName", "numeroInscriptio", "lastName", email, "dateOfBirth", "phoneNumber", address, "enrollmentDate", "parentId", "classroomId") VALUES ('Chloe', 'S007', 'Petit', 'chloe@student.com', '2012-07-18', '0645', 'Toulouse', '2024-09-01', 4, 1);
INSERT INTO activity (name, location, date, classroom) VALUES ('Sensory', 'Room1', '2026-05-25 10:00', 1);
INSERT INTO activity (name, location, date, classroom) VALUES ('Social', 'Room2', '2026-05-26 14:00', 2);
INSERT INTO activity (name, location, date, classroom) VALUES ('Yoga', 'Room3', '2026-05-27 09:00', 1);
INSERT INTO activity (name, location, date, classroom) VALUES ('Communication', 'Room4', '2026-05-28 15:00', 3);
INSERT INTO activity (name, location, date, classroom) VALUES ('Puzzle', 'Room5', '2026-05-29 11:00', 1);
INSERT INTO activity (name, location, date, classroom) VALUES ('PECS', 'Room6', '2026-05-30 10:30', 3);
INSERT INTO activity (name, location, date, classroom) VALUES ('Music', 'Room7', '2026-05-31 14:30', 2);
INSERT INTO activity (name, location, date, classroom) VALUES ('Drawing', 'Room8', '2026-06-01 13:00', 2);
INSERT INTO activity (name, location, date, classroom) VALUES ('Motor', 'Room9', '2026-06-02 10:00', 2);
INSERT INTO activity (name, location, date, classroom) VALUES ('Ball', 'Room10', '2026-06-03 15:30', 2);
