apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: eline2016/devopspfe-frontend:v15
        ports:
        - containerPort: 80
