apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: education
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
    spec:
      containers:
      - name: gateway
        image: devopspfe-gateway-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: LOG_LEVEL
          value: info
        - name: CORS_ORIGIN
          value: "*"
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: education
        - name: USER_SERVICE_HOST
          value: user-service
        - name: USER_SERVICE_PORT
          value: "3002"
        - name: AUTH_SERVICE_HOST
          value: auth-service
        - name: AUTH_SERVICE_PORT
          value: "3001"
        - name: ACTIVITY_SERVICE_HOST
          value: activity-service
        - name: ACTIVITY_SERVICE_PORT
          value: "3003"
        - name: PARENT_SERVICE_HOST
          value: parent-service
        - name: PARENT_SERVICE_PORT
          value: "3004"
        - name: STUDENT_SERVICE_HOST
          value: student-service
        - name: STUDENT_SERVICE_PORT
          value: "3005"
        - name: CLASSROOM_SERVICE_HOST
          value: classroom-service
        - name: CLASSROOM_SERVICE_PORT
          value: "3006"
        - name: TEACHER_SERVICE_HOST
          value: teacher-service
        - name: TEACHER_SERVICE_PORT
          value: "3007"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
