apiVersion: v1
kind: Service
metadata:
  name: gateway-backend-nodeport
  namespace: education
spec:
  type: NodePort
  selector:
    app: gateway-backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
