global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'education-cluster'
    monitor: 'devops-education'

rule_files:
  - '/etc/prometheus/rules/alerts.yml'

scrape_configs:
  # Prometheus Self Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kubernetes pods - education namespace - NO ANNOTATION FILTER
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - education
    relabel_configs:
      # Add pod labels
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
