global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'education-cluster'
    monitor: 'devops-education'

rule_files:
  - '/etc/prometheus/rules/alerts.yml'

scrape_configs:
  # Prometheus Self Monitoring ONLY
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
