#!/bin/bash
# 🚀 COMMANDES RAPIDES - PFE DEVOPS

echo "════════════════════════════════════════════════════════════"
echo "   DEVOPS EDUCATION PLATFORM - QUICK START COMMANDS"
echo "════════════════════════════════════════════════════════════"
echo ""

# ============ DÉVELOPPEMENT ============
echo "📦 DÉVELOPPEMENT (Docker Compose)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Construire tous les services:"
echo "   docker-compose build"
echo ""
echo "2. Démarrer tous les services:"
echo "   docker-compose up -d"
echo ""
echo "3. Vérifier le statut:"
echo "   docker-compose ps"
echo ""
echo "4. Voir les logs:"
echo "   docker-compose logs -f"
echo "   docker-compose logs -f gateway-backend"
echo ""
echo "5. Arrêter tout:"
echo "   docker-compose down"
echo ""
echo "6. Arrêter tout (y compris les volumes):"
echo "   docker-compose down -v"
echo ""

# ============ PRODUCTION ============
echo ""
echo "🎯 PRODUCTION (Kubernetes)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Créer le namespace:"
echo "   kubectl create namespace production"
echo ""
echo "2. Appliquer les secrets:"
echo "   kubectl apply -f kubernetes/secrets.yaml"
echo ""
echo "3. Appliquer les configmaps:"
echo "   kubectl apply -f kubernetes/configmap.yaml"
echo ""
echo "4. Déployer tout avec Kustomize:"
echo "   kubectl kustomize kubernetes/ | kubectl apply -f -"
echo ""
echo "5. Vérifier les pods:"
echo "   kubectl get pods"
echo "   kubectl get pods -w"
echo ""
echo "6. Vérifier les services:"
echo "   kubectl get svc"
echo ""
echo "7. Vérifier l'Ingress:"
echo "   kubectl get ingress"
echo ""
echo "8. Voir les logs d'un pod:"
echo "   kubectl logs <pod-name>"
echo "   kubectl logs <pod-name> -f"
echo ""
echo "9. Décrire un pod:"
echo "   kubectl describe pod <pod-name>"
echo ""
echo "10. Port forward pour accéder localement:"
echo "    kubectl port-forward svc/gateway 3000:3000"
echo "    kubectl port-forward svc/frontend 4200:4200"
echo ""

# ============ MONITORING ============
echo ""
echo "📊 MONITORING"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Accéder à Prometheus (docker-compose):"
echo "   http://localhost:9090"
echo ""
echo "2. Accéder à Grafana (docker-compose):"
echo "   http://localhost:3099"
echo "   Username: admin, Password: admin"
echo ""
echo "3. Accéder à Kibana (docker-compose):"
echo "   http://localhost:5601"
echo ""
echo "4. Port forward Grafana (Kubernetes):"
echo "   kubectl port-forward svc/grafana 3000:3000"
echo ""
echo "5. Port forward Prometheus (Kubernetes):"
echo "   kubectl port-forward svc/prometheus 9090:9090"
echo ""

# ============ DEBUGGING ============
echo ""
echo "🐛 DEBUGGING"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Vérifier la santé d'un service:"
echo "   curl http://localhost:3000/health"
echo ""
echo "2. Voir les événements du cluster:"
echo "   kubectl get events -w"
echo ""
echo "3. Vérifier les PVC (volumes):"
echo "   kubectl get pvc"
echo ""
echo "4. Vérifier les resource usage:"
echo "   kubectl top nodes"
echo "   kubectl top pods"
echo ""
echo "5. Entrer dans un pod:"
echo "   kubectl exec -it <pod-name> /bin/sh"
echo ""
echo "6. Voir les env vars d'un pod:"
echo "   kubectl exec <pod-name> -- env"
echo ""

# ============ IMAGES DOCKER ============
echo ""
echo "🐳 IMAGES DOCKER"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Lister toutes les images:"
echo "   docker images"
echo ""
echo "2. Lister les images du projet:"
echo "   docker images | grep devopspfe"
echo ""
echo "3. Push une image:"
echo "   docker push devopspfe-gateway-backend:latest"
echo ""
echo "4. Supprimer une image:"
echo "   docker rmi devopspfe-gateway-backend:latest"
echo ""

# ============ NETTOYAGE ============
echo ""
echo "🧹 NETTOYAGE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Supprimer tous les conteneurs arrêtés:"
echo "   docker container prune"
echo ""
echo "2. Supprimer toutes les images non utilisées:"
echo "   docker image prune"
echo ""
echo "3. Supprimer tous les volumes non utilisés:"
echo "   docker volume prune"
echo ""
echo "4. Espace disque utilisé par Docker:"
echo "   docker system df"
echo ""
echo "5. Nettoyer complètement Docker:"
echo "   docker system prune -a --volumes"
echo ""

# ============ ACCÈS AUX SERVICES ============
echo ""
echo "🌐 ACCÈS AUX SERVICES (Docker Compose)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Gateway (API):       http://localhost:3000"
echo "Auth Service:        http://localhost:3001"
echo "User Service:        http://localhost:3002"
echo "Activity Service:    http://localhost:3003"
echo "Parent Service:      http://localhost:3004"
echo "Student Service:     http://localhost:3005"
echo "Classroom Service:   http://localhost:3006"
echo "Teacher Service:     http://localhost:3007"
echo "Frontend:            http://localhost:4200"
echo ""
echo "PostgreSQL:          localhost:5432"
echo "Redis:               localhost:6379"
echo "RabbitMQ:            localhost:5672"
echo "RabbitMQ UI:         http://localhost:15672"
echo "Elasticsearch:       http://localhost:9200"
echo "Kibana:              http://localhost:5601"
echo "MinIO:               http://localhost:9000 / http://localhost:9001"
echo "Prometheus:          http://localhost:9090"
echo "Grafana:             http://localhost:3099"
echo ""

# ============ VOLUMES DOCKER COMPOSE ============
echo ""
echo "📁 VOLUMES (Docker Compose)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Lister tous les volumes:"
echo "   docker volume ls"
echo ""
echo "Inspecter un volume:"
echo "   docker volume inspect <volume-name>"
echo ""
echo "Supprimer un volume:"
echo "   docker volume rm <volume-name>"
echo ""

echo ""
echo "════════════════════════════════════════════════════════════"
echo "✅ Besoin d'aide? Consultez les fichiers:"
echo "   - PROJECT_CORRECTIONS_FINAL.md"
echo "   - RESUME_CORRECTIONS.md"
echo "════════════════════════════════════════════════════════════"
echo ""
