apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: education
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: education
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: education
        - name: POSTGRES_PASSWORD
          value: education
        - name: POSTGRES_DB
          value: education_db
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
      - name: activity-service
        image: eline2016/devopspfe-activity-service:v5
        ports:
        - containerPort: 3003
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: eline2016/devopspfe-auth-service:v3
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-service-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom-service
  template:
    metadata:
      labels:
        app: classroom-service
    spec:
      containers:
      - name: classroom-service
        image: eline2016/devopspfe-classroom-service:v4
        ports:
        - containerPort: 3006
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: eline2016/devopspfe-gateway-backend:v2
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-service-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parent-service
  template:
    metadata:
      labels:
        app: parent-service
    spec:
      containers:
      - name: parent-service
        image: eline2016/devopspfe-parent-service:v6
        ports:
        - containerPort: 3004
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
      - name: student-service
        image: eline2016/devopspfe-student-service:v4
        ports:
        - containerPort: 3005
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      containers:
      - name: teacher-service
        image: eline2016/devopspfe-teacher-service:v1
        ports:
        - containerPort: 3007
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: eline2016/devopspfe-user-service:v2
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          value: education
        - name: DB_PASSWORD
          value: education
        - name: DB_NAME
          value: education_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: frontend
        image: eline2016/devopspfe-frontend:v15
        ports:
        - containerPort: 80
