apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-service-deployment
  labels:
    app: classroom-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classroom-service
  template:
    metadata:
      labels:
        app: classroom-service
    spec:
      containers:
        - name: classroom-service
          image: devopspfe-classroom-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3006
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: education
---
apiVersion: v1
kind: Service
metadata:
  name: classroom-service
  labels:
    app: classroom-service
spec:
  selector:
    app: classroom-service
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006
  type: ClusterIP
