apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-service-deployment
  labels:
    app: parent-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parent-service
  template:
    metadata:
      labels:
        app: parent-service
    spec:
      containers:
        - name: parent-service
          image: devopspfe-parent-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: education
---
apiVersion: v1
kind: Service
metadata:
  name: parent-service
  labels:
    app: parent-service
spec:
  selector:
    app: parent-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP
