apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service-deployment
  labels:
    app: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: devopspfe-student-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: education
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-service
spec:
  selector:
    app: student-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
