apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: education-platform
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/imenH-cloud/devops-education-platform.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: education
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: 'Repository'
      value: 'devops-education-platform (Latest)'
    - name: 'Docker Hub'
      value: 'eline2016/* images'
